# Generated by Django 4.2.11 on 2024-05-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0005_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
