# Generated by Django 4.2.11 on 2024-08-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0009_official_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
