# Generated by Django 4.2.11 on 2024-08-16 03:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('official', '0011_remove_official_like_count_official_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='official',
            name='like_count',
        ),
        migrations.AddField(
            model_name='official',
            name='likes',
            field=models.ManyToManyField(related_name='liked_officials', to=settings.AUTH_USER_MODEL),
        ),
    ]
