# Generated by Django 4.2.11 on 2024-08-16 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('official', '0012_remove_official_like_count_official_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='official_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='official.official')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
