# Generated by Django 4.2.11 on 2024-08-21 15:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0015_remove_comment_image_comment_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
