# Generated by Django 4.2.11 on 2024-08-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official', '0016_alter_comment_featured_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
