# Generated by Django 4.2.11 on 2024-08-16 17:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_football_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='football',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
