# Generated by Django 4.2.11 on 2024-08-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_football_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='football',
            name='author',
        ),
        migrations.RemoveField(
            model_name='football',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='football',
            name='status',
        ),
    ]
